type Structures =
  | "bastion_remnant"
  | "buried_treasure"
  | "endcity"
  | "fortress"
  | "mansion"
  | "mineshaft"
  | "monument"
  | "fossil"
  | "ruins"
  | "outpost"
  | "portal"
  | "shipwreck"
  | "stronghold"
  | "pyramid"
  | "iglo"
  | "pyramid"
  | "swamp_hu"
  | "village";
export default Structures;
