"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
// https://minecraft.fandom.com/wiki/Effect#Effect_list
var EffectList;
(function (EffectList) {
    EffectList[EffectList["speed"] = 1] = "speed";
    EffectList[EffectList["slowness"] = 2] = "slowness";
    EffectList[EffectList["haste"] = 3] = "haste";
    EffectList[EffectList["mining_fatigue"] = 4] = "mining_fatigue";
    EffectList[EffectList["strength"] = 5] = "strength";
    EffectList[EffectList["instant_health"] = 6] = "instant_health";
    EffectList[EffectList["instant_damage"] = 7] = "instant_damage";
    EffectList[EffectList["jump_boost"] = 8] = "jump_boost";
    EffectList[EffectList["nausea"] = 9] = "nausea";
    EffectList[EffectList["regeneration"] = 10] = "regeneration";
    EffectList[EffectList["resistance"] = 11] = "resistance";
    EffectList[EffectList["fire_resistance"] = 12] = "fire_resistance";
    EffectList[EffectList["water_breathing"] = 13] = "water_breathing";
    EffectList[EffectList["invisibility"] = 14] = "invisibility";
    EffectList[EffectList["blindness"] = 15] = "blindness";
    EffectList[EffectList["night_vision"] = 16] = "night_vision";
    EffectList[EffectList["hunger"] = 17] = "hunger";
    EffectList[EffectList["weakness"] = 18] = "weakness";
    EffectList[EffectList["poison"] = 19] = "poison";
    EffectList[EffectList["wither"] = 20] = "wither";
    EffectList[EffectList["health_boost"] = 21] = "health_boost";
    EffectList[EffectList["absorption"] = 22] = "absorption";
    EffectList[EffectList["saturation"] = 23] = "saturation";
    EffectList[EffectList["glowing"] = 24] = "glowing";
    EffectList[EffectList["levitation"] = 25] = "levitation";
    EffectList[EffectList["luck"] = 26] = "luck";
    EffectList[EffectList["unluck"] = 27] = "unluck";
    EffectList[EffectList["slow_falling"] = 28] = "slow_falling";
    EffectList[EffectList["conduit_power"] = 29] = "conduit_power";
    EffectList[EffectList["dolphins_grace"] = 30] = "dolphins_grace";
    EffectList[EffectList["bad_omen"] = 31] = "bad_omen";
    EffectList[EffectList["hero_of_the_village"] = 32] = "hero_of_the_village";
})(EffectList || (EffectList = {}));
exports.default = EffectList;
